// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb3WLj-IzexFcX3uCyo_JVlaWfQah6pmM',
    appId: '1:386192819534:web:9068b656f5c90c0acc0a1f',
    messagingSenderId: '386192819534',
    projectId: 'internetapp-8738c',
    authDomain: 'internetapp-8738c.firebaseapp.com',
    storageBucket: 'internetapp-8738c.firebasestorage.app',
    measurementId: 'G-6ESL6HJQXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHPyRLq41nXq5DHUHKt3uhaYceLjc6tco',
    appId: '1:386192819534:android:6062d0300a925eedcc0a1f',
    messagingSenderId: '386192819534',
    projectId: 'internetapp-8738c',
    storageBucket: 'internetapp-8738c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3v_c9s39LD0urMFnv077KiKgNXA2wCjo',
    appId: '1:386192819534:ios:4df2a395c79e37d4cc0a1f',
    messagingSenderId: '386192819534',
    projectId: 'internetapp-8738c',
    storageBucket: 'internetapp-8738c.firebasestorage.app',
    iosBundleId: 'com.example.internetApplicationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3v_c9s39LD0urMFnv077KiKgNXA2wCjo',
    appId: '1:386192819534:ios:4df2a395c79e37d4cc0a1f',
    messagingSenderId: '386192819534',
    projectId: 'internetapp-8738c',
    storageBucket: 'internetapp-8738c.firebasestorage.app',
    iosBundleId: 'com.example.internetApplicationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb3WLj-IzexFcX3uCyo_JVlaWfQah6pmM',
    appId: '1:386192819534:web:095837781e9fce21cc0a1f',
    messagingSenderId: '386192819534',
    projectId: 'internetapp-8738c',
    authDomain: 'internetapp-8738c.firebaseapp.com',
    storageBucket: 'internetapp-8738c.firebasestorage.app',
    measurementId: 'G-SK8MV5MTQC',
  );
}
